### ISSUE TITLE
[Proposal] Legacy code release for backward compatability

### ISSUE THREAD

**Issue by ppasupat** [Farama-Foundation/miniwob-plusplus#24]
### Proposal 

Create a release containing the legacy code (before migrating to Farama).

### Motivation

A few projects depend on the old code structure. Examples include:
- [Workflow-Guided Exploration](https://github.com/stanfordnlp/wge)
- [DOM-Q-NET: Grounded RL on Structured Language](https://github.com/Sheng-J/DOM-Q-NET)
- [Environment Generation for Zero-Shot Compositional Reinforcement Learning](https://github.com/google-research/google-research/tree/master/compositional_rl)

To prevent breaking such codebases, it would be nice to create a release containing the legacy MiniWoB++ code.

### Pitch

Create a release at commit [833a477a8fbfbd2497e95fee019f76df2b9bd75e](https://github.com/Farama-Foundation/miniwob-plusplus/commit/833a477a8fbfbd2497e95fee019f76df2b9bd75e), which is right before the migration.

### Alternatives

The release should have minimal effects on the current code development.

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/miniwob-plusplus/issues) in the repo (**required**)

**Comment by pseudo-rnd-thoughts** [comment]
@jkterry1 Personally I have no issue with this. We can make a v0 release with the legacy code with v1 being the new version

**Comment by jkterry1** [comment]
Ya that's fine for me

**Comment by pseudo-rnd-thoughts** [comment]
@ppasupat How would you like to make this legacy release? Im guessing we want a pypi and github release

**Comment by ppasupat** [comment]
A GitHub release should be sufficient I think. PyPi would be a hassle since the code was not packaged that well, and for reproducibility, I don't want to modify the code too much.

**Comment by jkterry1** [comment]
Works for me

**Comment by ppasupat** [comment]
Thank you. Following up on this, I think my GitHub role does not allow me to create a release candidate. Could someone help create the release?

**Comment by pseudo-rnd-thoughts** [comment]
@ppasupat I have given you permissions to merge PRs etc as you are the main contributor. I think this should give you permissions to create releases just could you run the release notes pass jordan or myself as farama is trying to follow a standard operating procedure. If you don't have a copy of the SOP then just message or ask on Monday

**Comment by ppasupat** [comment]
The release is now live at https://github.com/Farama-Foundation/miniwob-plusplus/releases/tag/v0.1.
