### ISSUE TITLE
[Question] Will QAWoB be supported?

### ISSUE THREAD

**Issue by shuyanzhou** [Farama-Foundation/miniwob-plusplus#42]
### Question

Thanks for maintaining this wonderful benchmark. Besides MiniWoB(++), I am wondering if there is any plan on supporting QAWoB (http://proceedings.mlr.press/v70/shi17a/shi17a.pdf) in the future? If not, do you have any pointers to the data? Thanks!

**Comment by ppasupat** [comment]
Hi! We don't have a plan to add QAWoB right now, since it requires new infrastructure (i.e., request cache).
I can check with the authors of the paper regarding the data.
