### ISSUE TITLE
Hello, how can I use only plain text observations instead of using web pages?

### ISSUE THREAD

**Issue by SakuraXiaMF** [Farama-Foundation/miniwob-plusplus#91]
### Question

Hello, our environment is very user-friendly, but due to the cluster, I can't use Chrome driver. 
How can I work with an environment that uses only plain text?

**Comment by ppasupat** [comment]
(Answering for posterity)
The MiniWoB++ environments are browser-based tasks defined in HTML and JavaScript, so it requires something that can render web pages and execute JavaScript to function. We offer an engine based on ChromeDriver. Some projects like [Humphreys et al., 2022](https://arxiv.org/abs/2202.08137) only take the HTML/JavaScript and use a different driver like X11. But in any case some type of engine is needed.
